version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    env_file:
      - ./.env
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
    links:
      - "db:database"

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - fractal-app-volume:/data 
  link:
    environment:
      EXPOSE: frontend:3000 
    volumes:
      - fractal-link-volume:/root/.local/share/caddy
volumes:
  fractal-app-volume:
    external: true
    name: $APP_VOLUME_NAME
  fractal-link-volume:
    external: true
    name: $LINK_VOLUME_NAME

